[package]
name = "flip"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clipboard = "0.5.0"
rdev = "0.5.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
